apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd
  namespace: argocd
spec:
  channel: stable
  name: argocd
  source: myargocdoperator-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic